apiVersion: v1
kind: ServiceAccount
metadata:
  name: quick-k8s-manager
automountServiceAccountToken: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quick-k8s-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quick-k8s-manager
subjects:
- kind: ServiceAccount
  name: quick-k8s-manager
  namespace: quick-k8s
roleRef:
  kind: ClusterRole
  name: quick-k8s-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-k8s-manager-deployment
  labels:
    app: quick-k8s-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-k8s-manager
  template:
    metadata:
      labels:
        app: quick-k8s-manager
    spec:
      serviceAccountName: quick-k8s-manager
      automountServiceAccountToken: true
      containers:
      - name: quick-k8s-manager
        image: dimitrivinet/quick-k8s-v2:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: SECRET_KEY
            value: "6fa46d584e94e64322e9951378c2daccb3775107e8c1cc4bc4a28f7f366f9bde"
          - name: ALGORITHM
            value: "HS256"
          - name: TARGET_NAMESPACE
            value: "quick-k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: quick-k8s-manager-service
spec:
  selector:
    app: quick-k8s-manager
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  externalIPs:
    - 172.21.72.106
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quick-k8s-child
  namespace: quick-k8s
automountServiceAccountToken: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quick-k8s-child
  namespace: quick-k8s
rules:
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quick-k8s-child
  namespace: quick-k8s
subjects:
- kind: ServiceAccount
  name: quick-k8s-child
roleRef:
  kind: Role
  name: quick-k8s-child
  apiGroup: rbac.authorization.k8s.io
