apiVersion: v1
kind: ServiceAccount
metadata:
  name: quick-k8s-child
  namespace: quick-k8s-children
automountServiceAccountToken: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quick-k8s-child
  namespace: quick-k8s-children
rules:
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quick-k8s-child
  namespace: quick-k8s-children
subjects:
- kind: ServiceAccount
  name: quick-k8s-child
roleRef:
  kind: Role
  name: quick-k8s-child
  apiGroup: rbac.authorization.k8s.io
