---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quick-k8s-child
automountServiceAccountToken: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: quick-k8s
  name: quick-k8s-child
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: quick-k8s
  name: quick-k8s-child
subjects:
- kind: ServiceAccount
  name: quick-k8s-child
  namespace: quick-k8s
roleRef:
  kind: Role
  name: quick-k8s-child
  apiGroup: rbac.authorization.k8s.io
