apiVersion: v1
kind: Service
metadata:
  name: quick-k8s-manager-service
spec:
  selector:
    app: quick-k8s-manager
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
